### ISSUE TITLE
Notes and Orga Gergana

### ISSUE THREAD

**Issue by DaniGargya** [DaniGargya/dissertation#1]
Hey @gndaskalova !
It was good to talk to you yesterday. There are definitely more things that are at least a bit clearer.
Here is the link to the notes I took
https://github.com/DaniGargya/dissertation/blob/master/notes/200121_skype_gergana.docx

If there is anything you can think of that I missed please let me know :)
Cheers!

**Comment by gndaskalova** [comment]
Hey @DaniGargya 

Nice to talk to you too. That looks great and the next steps you've outlined all seem a good direction!

The only thing I thought I can mention is that you don't just need the sites with high accessibility scores, but also the low ones, as you need the "spectrum" for a comparison.

Have a nice day,
Gergana

**Comment by DaniGargya** [comment]
Hey @gndaskalova 
I have started writing the full plan, trying to incorporate the feedback from the one page outline and the one from the talk we had.  You can find it here
https://github.com/DaniGargya/dissertation/blob/master/documents/Dani_Gargya_full_plan_Jan20.docx

I would really appreciate some feedback on the research question as I am a bit lost what could maybe be analysed together or separately (eg Q1 and Q2, turnover and homogenization being two different questions? or whether I should include the Q3 with the taxa). 

That would then help me to develop my methods a bit better and actually writing out the models I am going to use (and of course drawing the graphs).

I am also aware that I can improve the writing and the flow, but for now I just wanted to get the things out. The intro definitively still needs a bit of a polish. 

Are you still free to do another skype talk on tuesday? 7pm works well for me; in case you are not skyping with the others I wouldn't mind an earlier time either.

If you prefer having sent an email to you, let me know please!

Have a good day/night,
Dani

**Comment by gndaskalova** [comment]
Hey @DaniGargya 

Great, thanks for sharing the file. I will take a look.

All good for a Skype on Tuesday - I am skyping with Shawn at 6pm, it might be more towards 30 minutes rather than an hour but I can't fully predict that in advance, so we can either say 7pm, or sometime between 6.30pm and 7pm, whatever you prefer, either way is fine by me.

Also the way my notifications are set up, I get an email whenever someone mentions my GitHub handle in a comment, so all fine by me to organise these things over GitHub, since that way I both get an email and also there is a more condensed record of what we've discussed that is not spread all over my emails.

**Comment by DaniGargya** [comment]
Hey @gndaskalova ,
just for your infomation I have added the meeting notes from last night here.

https://github.com/DaniGargya/dissertation/blob/master/notes/200128_skype_gergana.docx

Have a good day!

**Comment by gndaskalova** [comment]
Great @DaniGargya !

**Comment by DaniGargya** [comment]
Hey @gndaskalova !
I had a meeting with Isla today, you can find the notes here: https://github.com/DaniGargya/dissertation/blob/master/notes/200206_meeting_Isla.docx

We were also talking about the data that I will need to use. At the moment I have started to look at the metadata (BioTIMEMetadata_02_04_2018.csv). I also had a wee peak at the actual data (BioTIMEQuery02_04_2018.csv) both what they provide in csv form on their website. I was wondering whether this is all the data I will need? Isla mentioned that you are working with a subset of data you got through the SQL database? Does this provide you with any other essential data?

The other question I discussed with Isla was the criteria for the data to include. I was thinking of 
o	Time frame in which studies must be: 1990 till today
o	Minimum duration: 5 years
o	Minimum time points: 3

Could you please give me some feedback what you think about those criteria? 

Thanks and talk to you soon,
Dani

**Comment by DaniGargya** [comment]
Hey @gndaskalova ,
Hope you arrived back well in Scotland!

I have finally managed to produce a first draft of preregistration. You can find it here
https://github.com/DaniGargya/dissertation/blob/master/documents/DG_draft_preregistration_Feb20.docx

I have added questions on the document directly. For some of them, it might be easier to quickly talk about them either in person or on the phone (I will be in Germany from this Wednesday to next Monday). Let me know what works best for you please :)

Have a good day and talk to you soon!
Dani

**Comment by gndaskalova** [comment]
Hey @DaniGargya 

Thanks for sharing the preregistration and hope you have a nice time in Germany! This week is a bit hectic for me so perhaps we could meet in person on Tuesday once you're back? Or I could also do Wednesday or Friday if you prefer. I'll take a look at your pre-registration before we meet so that we can discuss it then.

Gergana

**Comment by DaniGargya** [comment]
Hey @gndaskalova 

Tuesday sounds good! are you free before 1 or after 5?

See you then,
Dani

**Comment by DaniGargya** [comment]
Hey @gndaskalova 
Does tomorrow at 5 pm work for you?

**Comment by gndaskalova** [comment]
Hey @DaniGargya sorry for the late response - can we do 12 then? I am going to a comedy show from 5.30pm.

**Comment by DaniGargya** [comment]
12 sounds good! Murchiston house cafe area?

**Comment by gndaskalova** [comment]
See you there!

**Comment by DaniGargya** [comment]
Hey @gndaskalova !
would you be free sometime tomorrow before or after coding club? I have some remaining questions for the preregistration, but I don't think it will take too long.. 
That'd be great!
