### ISSUE TITLE
Notes and orga Isla

### ISSUE THREAD

**Issue by DaniGargya** [DaniGargya/dissertation#2]
Hey @IslaMS ,
I have just written up the meeting notes here, if you want to have a look:

https://github.com/DaniGargya/dissertation/blob/master/notes/200306_meeting_Isla.docx

Did you manage to access the repo?

I will let you know once I have a final version for my preregistration.

Have a good weekend,
Dani

**Comment by IslaMS** [comment]
I am all good on repo access now.  Deleting both your and Shawn's repos restarting my computer and starting again with cloning did the trick.  

Thanks for the notes.  I think you are very much on track.  

And happy weekend!

Isla

**Comment by IslaMS** [comment]
Hey Dani,
Hi @DaniGargya,

I briefly communicated with @gndaskalova yesterday.  Here is what she recommends:

1) Read up about rarefaction and check out in detail the methods in Blowes et al. 2019.
https://science.sciencemag.org/content/366/6463/339.editor-summary

2) Plot the area of each of the studies that you are using using a histogram or what have you.  Are these locations spread across quite a large region or are they in quite a discrete area?  Calculate the number of studies that have "permanent" plots and how many plots they have versus just being "one general location" where the exact sample location might change over time.  This helps you figure out whether you need to rarefy your samples or whether you want to remove some studies, but then not rarefy your data.  

3) Have a go at calculating temporal beta diversity using your metrics of choice with the vegan package and don't worry about rarefaction at the moment (the thing that takes a long time to do).

4) If you decide you do need rarefied data down the road, you can speak with Gergana about that when she is back to Edinburgh and free.  

And remember that you can set up your plots and analyses with fake data randomly generated between 0 and 1, while you are figuring out the calculation of your temporal beta diversity metric.

Gergana can chip in here if she wants to clarify or suggest other ideas.

Isla

**Comment by DaniGargya** [comment]
Hey @IslaMS !
thanks for the info. I will have a go and probably come back with some questions soon.

**Comment by DaniGargya** [comment]
Hey @IslaMS ,
sorry for the short notice but would you be free sometime today after the TS meeting?
See you soon,
Dani
