### ISSUE TITLE
Kind of data presents (almost)

### ISSUE THREAD

**Issue by DaniGargya** [DaniGargya/dissertation#5]
Hey @IslaMS and @gndaskalova ,

I ran my model and produced some results! But there are loooads of things to fix before they mean anything.

But first things first, here are some graphs and part of the model output

![raincloud_taxa_graph](https://user-images.githubusercontent.com/32903053/78591435-53a5cd80-783b-11ea-9ae7-fdabb41f0cc0.png)

![mo_tu_graph1](https://user-images.githubusercontent.com/32903053/78591447-59031800-783b-11ea-836c-844a4c378b84.png)

![mo_tu_graph1_zoom](https://user-images.githubusercontent.com/32903053/78591457-5bfe0880-783b-11ea-94f0-5d85171a3ebf.png)

<img width="404" alt="tu_mo_outputs" src="https://user-images.githubusercontent.com/32903053/78593448-8c937180-783e-11ea-928b-8805c8e2f9ee.png">

So, I figured out a couple of things which have gone wrong:
- The distribution of the accessibility score is not normal at all. There are almost no values representing low acc. Even when logging the scaled accessibility score it the distribution does not look normal. Any idea what I can do?

- does it matter if my other variables are not normally distributed either (eg. Jtu, area, duration, hpd)?

- I realized that for calculating the jaccard value I didn't consider the abundance_type it is recorded in, so for some plots it gives me NA values. In the schange workshop I saw that they changed the functions based on the abundance_type but I couldn't match the types that are present in my data (count, density, NA) to what they were using (count, presence, biomass). The density ones in mine are just two studies/ 15 plots. But I don't really know what to do with all the NAs?

Have a good night,
Dani

**Comment by DaniGargya** [comment]
Hey @IslaMS and @gndaskalova ,
i managed to consider the abundacne type so I don't get NA values anymore when calculating the jaccard. I ran the model again and now it looks better!


![posterior_estimate_mo_tu2](https://user-images.githubusercontent.com/32903053/78888055-e2436600-7a58-11ea-9d21-0b70f54d43c2.png)


the trace plots of the model don't look good at all, but it already takes a long time to run the model. so I didn't want to increase the iterations yet.

also when I am trying to visualise, it still looks super weird:

![mo_tu2_graph](https://user-images.githubusercontent.com/32903053/78887718-46195f00-7a58-11ea-80df-ba4dca3abd9f.png)

![mo_tu_2_graph_hpd](https://user-images.githubusercontent.com/32903053/78888264-31899680-7a59-11ea-8e25-4aa2c029a0bc.png)

**I am still struggling to get my head around interpreting all the outputs from the brms model. Any chance one of you is free tomorrow before or after the lab meeting?**

Have a lovely day,
Dani

**Comment by DaniGargya** [comment]
@IslaMS  and @gndaskalova 

Also when I try to run any other model (changing the fixed effects, even simpler ones), I get this error:
Error in unserialize(socklist[[n]]) : error reading from connection Error in serialize(data, node$con, xdr = FALSE) : error writing to connection

I've tried to look it up but it seems to be a very general error.. any ideas how to get around it?

**Comment by IslaMS** [comment]
Hi @DaniGargya,

Did you want to meet with me this afternoon?

Isla

**Comment by DaniGargya** [comment]
Hi @IslaMS 
Would you also be free on monday? I would like to try and wrap my head around a couple more things first..

**Comment by IslaMS** [comment]
Hi @DaniGargya,

I should be around on Monday.  That works for me.  

Isla

**Comment by DaniGargya** [comment]
Hey @IslaMS ,

in the end I am going to talk to Gergana tomorrow. So, I will catch up with you more towards the end of this week?

Dani

**Comment by IslaMS** [comment]
Hi @DaniGargya,

Sounds good.  Just let me know if you want to meet with me.

Isla
